# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - good first issue
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: Enhancements 
      labels:
        - Semver-Minor
        - enhancement
    - title: Bug Fixes
      labels:
        - Semver-Patch
        - bug
    - title: Deprecations
      labels:
        - deprecation
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Documentation
      labels:
        - documentation

